[package]
name = "rust_srt_extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
native-dialog = "0.7.0"
regex = "1.10.4"
